# Generated by Django 3.2.23 on 2024-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0008_auto_20240701_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена, розничная'),
        ),
        migrations.AddField(
            model_name='good',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена, розничная'),
        ),
    ]
