# Generated by Django 3.2.23 on 2024-08-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0009_auto_20240829_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена, оптовая'),
        ),
    ]
