# Generated by Django 3.2.23 on 2025-02-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0013_auto_20250124_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Описание'),
        ),
    ]
