# Generated by Django 3.2.23 on 2025-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0014_alter_good_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='SEO-description'),
        ),
        migrations.AddField(
            model_name='good',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='SEO-keywords'),
        ),
        migrations.AddField(
            model_name='good',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='SEO-title'),
        ),
    ]
