# Generated by Django 3.2.23 on 2025-04-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0015_auto_20250411_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='seo_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<description>'),
        ),
        migrations.AlterField(
            model_name='good',
            name='seo_keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<keywords>'),
        ),
        migrations.AlterField(
            model_name='good',
            name='seo_title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<title>'),
        ),
    ]
