# Generated by Django 3.2.23 on 2025-04-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0016_auto_20250411_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<description>'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<keywords>'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<title>'),
        ),
    ]
