# Generated by Django 3.2.23 on 2025-04-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0018_seodefaults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEODefaults',
        ),
    ]
