# Generated by Django 3.2.23 on 2025-04-17 04:37

import const_app.commons
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0019_delete_seodefaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='okei',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ед.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, default=const_app.commons.fetch_seo_description_category, null=True, verbose_name='<description>'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_keywords',
            field=models.TextField(blank=True, default=const_app.commons.fetch_seo_keywords_category, null=True, verbose_name='<keywords>'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title',
            field=models.TextField(blank=True, default=const_app.commons.fetch_seo_title_category, null=True, verbose_name='<title>'),
        ),
        migrations.AlterField(
            model_name='good',
            name='seo_description',
            field=models.TextField(blank=True, default=const_app.commons.fetch_seo_description_good, null=True, verbose_name='<description>'),
        ),
        migrations.AlterField(
            model_name='good',
            name='seo_keywords',
            field=models.TextField(blank=True, default=const_app.commons.fetch_seo_keywords_good, null=True, verbose_name='<keywords>'),
        ),
        migrations.AlterField(
            model_name='good',
            name='seo_title',
            field=models.TextField(blank=True, default=const_app.commons.fetch_seo_title_good, null=True, verbose_name='<title>'),
        ),
    ]
