# Generated by Django 3.2.23 on 2025-05-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0020_auto_20250417_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Высота, м'),
        ),
        migrations.AddField(
            model_name='good',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Длина, м'),
        ),
        migrations.AddField(
            model_name='good',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='good',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Ширина, м'),
        ),
    ]
