# Generated by Django 3.2.23 on 2025-06-17 05:51

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0021_auto_20250513_0722'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='good',
            managers=[
                ('active_items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
