# Generated by Django 3.2.23 on 2025-06-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0022_auto_20250617_0851'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='good',
            managers=[
            ],
        ),
    ]
