# Generated by Django 3.2.23 on 2024-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20240216_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, null=True, verbose_name='Наименование'),
        ),
    ]
