# Generated by Django 3.2.23 on 2024-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_auto_20240216_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12, verbose_name='ИНН'),
        ),
    ]
