# Generated by Django 3.2.23 on 2024-02-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='client_app.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$WhJoIXwMaSi8nCs85oYMmU$iWxcn4OX6sq7qhgNDllezZP8gWf4FssBrVvbutKbbYE=', max_length=128, verbose_name='password'),
        ),
    ]
