# Generated by Django 3.2.23 on 2024-02-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20240215_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$rFQZ5OusObU1kWQFjL2IrN$ch9OBjj9Ef/iMjF6SXZolGfwRZ7jhGj7OusBOk4LZZM=', max_length=128, verbose_name='password'),
        ),
    ]
