# Generated by Django 3.2.23 on 2024-02-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$eigNFl2p0kHlqdL8iaF1K2$J4e5TrVaLYQQBhY4ZYUQS9SQVi2sh37B0Wd5W2sUVJ4=', max_length=128, verbose_name='password'),
        ),
    ]
