# Generated by Django 3.2.23 on 2024-02-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$9saPY2aB6zXmpPpJaeoB5W$LkGkbJzZy8o9qAQDUUNil+jrDLHe9hZ77NG9hOoDWxc=', max_length=128, verbose_name='password'),
        ),
    ]
