# Generated by Django 3.2.23 on 2024-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$SuxjKvKMa0dWmcQTJMDyEH$91anjmRyEFLQxfQ0dJgm/AMJ3IodneYeFmCw1CS9hcQ=', max_length=128, verbose_name='password'),
        ),
    ]
