# Generated by Django 3.2.23 on 2024-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$rtxyxA9b5mJc86AjlmNa7P$nvPHSU/P2P0WwetxigoSsFYNYDzjJRDZYQOCLTAE+Q0=', max_length=128, verbose_name='password'),
        ),
    ]
