# Generated by Django 3.2.23 on 2024-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$K5CXWDh3DPqquu4yGBzGNC$FVQayYgJScL0XDtmMlnW6YtRifqL6Na+KYDz17cwvVM=', max_length=128, verbose_name='password'),
        ),
    ]
