# Generated by Django 3.2.23 on 2024-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$qhABm1LNveRFWAB2CGKk9k$gQoSKGsS2J6kd8c7Q6NpgbdYIrR7zr9dqk69ckoAhSc=', max_length=128, verbose_name='password'),
        ),
    ]
