# Generated by Django 3.2.23 on 2024-06-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_auto_20240228_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$uphx0aFJkfaVPKDScazhFS$zq/EUWBek8MBdmub7LGDRHX/u0yuE6ULCvKasb8/35Q=', max_length=128, verbose_name='password'),
        ),
    ]
