# Generated by Django 3.2.23 on 2024-08-30 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$620IEtfXPcQ5P7lxTaVnhA$p0XQl0W0XRSzQcZX3euZs545DsMV3O0SyUflErR4vdo=', max_length=128, verbose_name='password'),
        ),
    ]
