# Generated by Django 3.2.23 on 2024-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$OkVAqEDFIXOob0tiRAzrrS$5ZIYnZapXXJ9d6BLl9oDJ9rrO1Zbkvtrq+wrgylR1J4=', max_length=128, verbose_name='password'),
        ),
    ]
