# Generated by Django 3.2.23 on 2024-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$RCA8Pe82nRyfNUEhmzEySL$LfQKPr4wYGUw7EBR6Nvj30OX1/FMPLqYWLgtzoyeStA=', max_length=128, verbose_name='password'),
        ),
    ]
