# Generated by Django 3.2.23 on 2024-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$Dr5dUUKbfgCuhYokgvIcdB$cMro0FT9eA0BMKvw5Rq8QZcFm/TBq5sTMp9BTN7Yi3I=', max_length=128, verbose_name='password'),
        ),
    ]
