# Generated by Django 3.2.23 on 2024-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$EIUNrdN7YwKrWUVvxtHFug$UOKqQMtjs7xm4Xei/9FSlHO7fobBUVCqEUGFDtv2kJs=', max_length=128, verbose_name='password'),
        ),
    ]
