# Generated by Django 3.2.23 on 2025-01-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$AWY3Qcv7lHEeC3Hn6l7Vny$KzB7JQOc6RV5WQ9to6Nd2PBTWXuUDiPkoJp6JvToAvw=', max_length=128, verbose_name='password'),
        ),
    ]
