# Generated by Django 3.2.23 on 2025-01-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$CLE1kuFZWd7ihkRLy6Pxzq$IDHL1aVFhLMY53zgnvb6FICee5sSR+4SqmA9uEDyjLQ=', max_length=128, verbose_name='password'),
        ),
    ]
