# Generated by Django 3.2.23 on 2025-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$dmS68D6K9n0ozSzSNfWYfB$BC6boPltze2pbAotmd6Ai4TitIrljWJqYYb3fDKHFTQ=', max_length=128, verbose_name='password'),
        ),
    ]
