# Generated by Django 3.2.23 on 2025-01-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$XpcSAVwbUpsAbiBOhPgIAA$6c3x6zlc5kip91GPyNdGULav+53km5Q5NnGTJ8m2McY=', max_length=128, verbose_name='password'),
        ),
    ]
