# Generated by Django 3.2.23 on 2025-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$SDmUxg9rSiWo0o02i4kGMI$1t3HEkTPjSJkwtYHo0RoiNL58W4cfEvpA7vlsgxl2T0=', max_length=128, verbose_name='password'),
        ),
    ]
