# Generated by Django 3.2.23 on 2025-02-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$sCZc7GmQuVPCBAmNsnW4fi$GPrpPI89aOVgms3OX+UAG4rFxefOJHRw1vdzSRz6yss=', max_length=128, verbose_name='password'),
        ),
    ]
