# Generated by Django 3.2.23 on 2025-02-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$QOIIKJLOTBZ9uSnbLnZyxW$afq7e8Jxu4eZ18lmTEBbMJFrbIxKb5Bk/VLvUsRiiHk=', max_length=128, verbose_name='password'),
        ),
    ]
