# Generated by Django 3.2.23 on 2025-02-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$ppwRXN5isigZrnRIuIkm4C$MTz6NY7MDd3V5Q0LIv+7DAoSCcMWKBnjq6IZQOi2PMI=', max_length=128, verbose_name='password'),
        ),
    ]
