# Generated by Django 3.2.23 on 2025-02-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$qA9qqUsKeLisc9rIPaUyeX$X99iKYy2+5v3Rk7ig+IrwG30AWtAe2dSQjDE4eHnIMk=', max_length=128, verbose_name='password'),
        ),
    ]
