# Generated by Django 3.2.23 on 2025-02-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$SMwBYkjv8HZxCo0OQLbszq$gllvfc6vH+zaMS0UZBcJVl55x5KLUi5FT728eE3w/Aw=', max_length=128, verbose_name='password'),
        ),
    ]
