# Generated by Django 3.2.23 on 2025-02-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$rzzFLnMc2vVQKVkJdkvwcn$ioFbXrAmEEDm/3VvA0ZaRSTBJ+BV9Jlh8A/OBPYFWgI=', max_length=128, verbose_name='password'),
        ),
    ]
