# Generated by Django 3.2.23 on 2025-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reseller',
            field=models.BooleanField(default=False, verbose_name='Это оптовик'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$0BJdsL6TrwOhzEJzgAC5iU$t+m36ds7hbj6iVxhA51FJy5lRsB1x76tkT29TjXYmSU=', max_length=128, verbose_name='password'),
        ),
    ]
