# Generated by Django 3.2.23 on 2025-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_auto_20250304_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$0lff2oVqhTh0OC52yYlUny$X2koQp1Nlyh6m7IXz9fewx63AkzoL0/aug8cK5EIyus=', max_length=128, verbose_name='password'),
        ),
    ]
