# Generated by Django 3.2.23 on 2025-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$vJl5mZK3pyer6i4CZdgTyS$Vzbw3wRJcQukbweuDaP34f7xyXKgGMqBWCLrhiZB49U=', max_length=128, verbose_name='password'),
        ),
    ]
