<<<<<<< HEAD
# Generated by Django 3.2.23 on 2025-04-11 06:35
=======
# Generated by Django 3.2.23 on 2025-04-11 10:47
>>>>>>> 490474c5e84e1df366edc1a5029da98c750196aa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
<<<<<<< HEAD
            field=models.CharField(default='pbkdf2_sha256$260000$AIBmcUaO85C71S1lhMRpYA$/P9v5Q9jx/ELSyEnc6jF2U9crMBuo+TgNYEIFBoE38o=', max_length=128, verbose_name='password'),
=======
            field=models.CharField(default='pbkdf2_sha256$260000$vJl5mZK3pyer6i4CZdgTyS$Vzbw3wRJcQukbweuDaP34f7xyXKgGMqBWCLrhiZB49U=', max_length=128, verbose_name='password'),
>>>>>>> 490474c5e84e1df366edc1a5029da98c750196aa
        ),
    ]
