# Generated by Django 3.2.23 on 2025-04-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$ZlfnA6IObPWlW0Lz2svMm5$EGRgyMliDcT0EeI9WMhr7P6xeORG2sIut4LEr71Gymg=', max_length=128, verbose_name='password'),
        ),
    ]
