# Generated by Django 3.2.23 on 2025-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$vZgQ1bychnnenp9Kx6PZnH$lEyoBp7q7gr9n0j5xUQrhG6CCvgYkgpcJdJse3rV9+A=', max_length=128, verbose_name='password'),
        ),
    ]
