<<<<<<< HEAD
# Generated by Django 3.2.23 on 2025-04-11 06:49
=======
# Generated by Django 3.2.23 on 2025-04-11 10:51
>>>>>>> 490474c5e84e1df366edc1a5029da98c750196aa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
<<<<<<< HEAD
            field=models.CharField(default='pbkdf2_sha256$260000$vZgQ1bychnnenp9Kx6PZnH$lEyoBp7q7gr9n0j5xUQrhG6CCvgYkgpcJdJse3rV9+A=', max_length=128, verbose_name='password'),
=======
            field=models.CharField(default='pbkdf2_sha256$260000$ZlfnA6IObPWlW0Lz2svMm5$EGRgyMliDcT0EeI9WMhr7P6xeORG2sIut4LEr71Gymg=', max_length=128, verbose_name='password'),
>>>>>>> 490474c5e84e1df366edc1a5029da98c750196aa
        ),
    ]
