# Generated by Django 3.2.23 on 2025-04-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0033_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$NfJfaJEdcc4Ru5l5xgXrfW$uAzlMXvyy8b3GHJSSXwDT3mgnRc1vLF248/sZvFTlfQ=",
                max_length=128,
                verbose_name="password",
            ),
        ),
    ]
