<<<<<<< HEAD
# Generated by Django 3.2.23 on 2025-04-14 03:57
=======
# Generated by Django 3.2.23 on 2025-04-12 04:06
>>>>>>> c9c8f448828ecc2aa136899d58a6ba6f5b63ba89

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0033_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
<<<<<<< HEAD
            field=models.CharField(default='pbkdf2_sha256$260000$NfJfaJEdcc4Ru5l5xgXrfW$uAzlMXvyy8b3GHJSSXwDT3mgnRc1vLF248/sZvFTlfQ=', max_length=128, verbose_name='password'),
=======
            field=models.CharField(default='pbkdf2_sha256$260000$lFT1QcWza9SCmn5MjWklRj$oAx9jsO87LIuDi4hCxaZM4Bi9Fc1L6c4d7SP1FWlem0=', max_length=128, verbose_name='password'),
>>>>>>> c9c8f448828ecc2aa136899d58a6ba6f5b63ba89
        ),
    ]
