# Generated by Django 3.2.23 on 2025-04-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$M6eqW1fmED3iFQmXNcr2pP$DMT6fCDi+7IQJNvXy2alSZi7fF8XEJa1sT3S3YpmF0M=', max_length=128, verbose_name='password'),
        ),
    ]
