# Generated by Django 3.2.23 on 2025-04-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$qEXkIIGgfSCIR5VuoIjFZ8$43FzxBEuhxsu5RdWLVvJiQuFa8kr9smx3SJLKShRAqc=', max_length=128, verbose_name='password'),
        ),
    ]
