# Generated by Django 3.2.23 on 2025-05-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0037_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$g3v0X5zCTjfSFi2LwISZNE$iYEyNfRFb61jbTFPHSIJ4XaiAsNE1hU+8qE/2gGIX74=', max_length=128, verbose_name='password'),
        ),
    ]
