# Generated by Django 3.2.23 on 2025-05-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$6pv4hoOSj2uodC4E1icr2w$jWCqCMhk32r0/h6ilmoeLXvEU75tvILtxH3Q7WNAWJk=', max_length=128, verbose_name='password'),
        ),
    ]
