# Generated by Django 3.2.23 on 2025-06-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$ngMa7oSiR8vwh7rrQb0Ew8$cR+9XfXBCzWW8j3fj7pIKvg7TWKPZggEh7pUa8u6aIE=', max_length=128, verbose_name='password'),
        ),
    ]
