# Generated by Django 3.2.23 on 2025-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0040_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$7hv169O54gjrEBuNER3XeW$kgn/HrNHjnlMf9SdUwR2hbrvdixhy+wQwdFYmR0hM54=', max_length=128, verbose_name='password'),
        ),
    ]
