# Generated by Django 3.2.23 on 2025-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0041_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$0HkSU2oD7DhgZfMwHn1RnV$fzgxdr5ZOAf/jrf5lq0oZkcfrwfv3R5lhhX92O9rDHU=', max_length=128, verbose_name='password'),
        ),
    ]
