# Generated by Django 3.2.23 on 2024-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_client_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, null=True, verbose_name='Наименование'),
        ),
    ]
