# Generated by Django 3.2.23 on 2024-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_reseller',
            field=models.BooleanField(default=False, verbose_name='Это оптовик'),
        ),
    ]
