# Generated by Django 3.2.23 on 2024-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_auto_20240905_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.IntegerField(blank=True, default=0, verbose_name='ИНН'),
        ),
    ]
